### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by stephenfangzhen** [PunkMale/ECAPA-TDNN-CNCeleb#1]
![56BB8017E61763C6CAF2819F5705C8AC](https://github.com/PunkMale/ECAPA-TDNN-CNCeleb/assets/150210919/7bc4db96-3740-4fb3-9057-e3cc8bf0b3d7)
你好，小白想向您问一下这个数据集解压之后是这样吗？

**Comment by stephenfangzhen** [comment]
![Uploading 56BB8017E61763C6CAF2819F5705C8AC.png…]()

**Comment by PunkMale** [comment]
你好，你展示的似乎只有cn1的数据，我这边的数据结构是这样：
<img width="530" alt="image" src="https://github.com/PunkMale/ECAPA-TDNN-CNCeleb/assets/44804926/c4342cfa-41e9-4879-a7df-027a6deaa1e2">
