### ISSUE TITLE
Inquiry Regarding Access to train.csv in ECAPA-TDNN and CN-Celeb Datasets

### ISSUE THREAD

**Issue by ZhaoQinlao** [PunkMale/ECAPA-TDNN-CNCeleb#2]
As a newcomer to ECAPA-TDNN and CN-Celeb datasets, I am seeking clarification on how to access the 'train.csv' file. Despite searching through the official dataset repositories, I have been unable to locate this specific file. Could you please provide guidance on how to obtain it?
Any assistance or direction on how to access the 'train.csv' file would be greatly appreciated. Thank you for your attention to this matter.

**Comment by PunkMale** [comment]
你好！我是参考[sunine](https://gitlab.com/csltstu/sunine/-/blob/master/egs/voxceleb/v2/run.sh)这个脚本的stage1和stage2构建train.csv和trails.lst的。
因为voxceleb和cnceleb的文件夹结构基本一致，所以换个路径就行。不过要注意的是在sunine框架中可能只检测wav后缀。相应的生成脚本在run.sh文件同级目录的的local目录中，你在里面把wav改成flac即可。
最后的形式是这样：
![image](https://github.com/PunkMale/ECAPA-TDNN-CNCeleb/assets/44804926/a155453f-aa07-483c-a3bd-662189b6ff6a)
如果不行的话我把我的文件传到仓库中。

祝好！

**Comment by ZhaoQinlao** [comment]
非常感谢您的回复，参看了您的回复后，我用[sunine](https://gitlab.com/csltstu/sunine/-/blob/master/steps/build_datalist.py?ref_type=heads)的step/build_datalist.py生成了一个类似的train.csv的文件，这对我帮助很大。
